<a href="https://colab.research.google.com/github/JekugaBrandon/DataScientistLife/blob/master/beginners_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print("Tensor Version:", tf.__version__)

Tensor Version: 2.18.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 225.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.13218167, -0.24457642,  0.55736053, -0.10174289,  0.02267336,
         0.65054864,  0.2243191 , -0.07238557, -0.5440508 ,  0.3624844 ]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.09744736, 0.06685688, 0.1490812 , 0.07712194, 0.08733959,
        0.16364169, 0.10685254, 0.07941959, 0.04955484, 0.12268437]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(1.8100761)

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8591 - loss: 0.4733
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9576 - loss: 0.1457
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9675 - loss: 0.1056
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9730 - loss: 0.0867
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9784 - loss: 0.0693


In [11]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9764 - loss: 0.0772


[0.07715468108654022, 0.9764000177383423]

In [13]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.1067827e-07, 8.7943567e-07, 3.7680099e-06, 2.6162621e-04,
        2.6833091e-09, 2.6382834e-06, 2.5155412e-11, 9.9968588e-01,
        3.9430233e-06, 4.1015948e-05],
       [2.6660493e-07, 1.4232055e-04, 9.9983776e-01, 1.6288097e-05,
        4.1467310e-13, 2.8098559e-06, 6.8793206e-08, 4.1967020e-12,
        4.7418624e-07, 9.3871708e-14],
       [7.5563702e-07, 9.9732411e-01, 3.3004305e-04, 8.0948666e-05,
        1.7154345e-04, 2.6377860e-05, 2.8408449e-05, 6.3319184e-04,
        1.3991138e-03, 5.3971207e-06],
       [9.9998772e-01, 1.3883761e-09, 5.9099955e-07, 5.8129977e-08,
        8.3198294e-08, 1.6589985e-06, 8.3917712e-06, 5.8935274e-07,
        4.6372092e-10, 9.5967221e-07],
       [2.7680897e-05, 3.5548688e-08, 4.4347700e-05, 4.1189185e-07,
        9.8777497e-01, 1.0961818e-06, 1.2655690e-05, 3.8601705e-05,
        3.2996363e-06, 1.2096903e-02]], dtype=float32)>